name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - uses: actions/cache@v4
        with:
          path: ./testbin
          key: ${{ runner.os }}-testbin

      - uses: actions/cache@v4
        with:
          path: ./bin
          key: ${{ runner.os }}-bin

      - name: Run tests
        run: |
          make test